from __future__ import annotations

import base64
import json
import tempfile
import unittest
from pathlib import Path

from ._tool_test_harness import build_env, run_tool


class PptxToolSmokeTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.env = build_env()
        cls.tmpdir_obj = tempfile.TemporaryDirectory(prefix="pptx-tool-smoke-")
        cls.tmpdir = Path(cls.tmpdir_obj.name)

    @classmethod
    def tearDownClass(cls) -> None:
        cls.tmpdir_obj.cleanup()

    def run_tool(self, *args: str):
        return run_tool("pptx-tool", *args, env=self.env)

    def test_create_info_extract(self) -> None:
        deck = self.tmpdir / "deck.pptx"
        create = self.run_tool(
            "create",
            "--title",
            "Smoke Deck",
            "--text",
            "# Slide One\nHello slide\n---\n# Slide Two\nWorld",
            "-o",
            str(deck),
        )
        self.assertEqual(create.returncode, 0, msg=create.stderr)
        self.assertTrue(deck.exists())

        info = self.run_tool("info", str(deck))
        self.assertEqual(info.returncode, 0, msg=info.stderr)
        meta = json.loads(info.stdout)
        self.assertGreaterEqual(meta["slide_count"], 2)

        extracted = self.run_tool("extract", str(deck))
        self.assertEqual(extracted.returncode, 0, msg=extracted.stderr)
        self.assertIn("Hello slide", extracted.stdout)
        self.assertIn("World", extracted.stdout)

    def test_extract_invalid_slide_fails(self) -> None:
        deck = self.tmpdir / "bad-slide.pptx"
        create = self.run_tool("create", "--title", "One", "-o", str(deck))
        self.assertEqual(create.returncode, 0, msg=create.stderr)

        result = self.run_tool("extract", str(deck), "--slide", "99")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("out of range", result.stderr)

    def test_structured_deck_elements_metadata_lint_and_contact_sheet(self) -> None:
        image = self.tmpdir / "pixel.png"
        image.write_bytes(base64.b64decode(
            "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2nZ8AAAAASUVORK5CYII="
        ))
        spec = self.tmpdir / "deck-spec.json"
        spec.write_text(json.dumps({
            "title": "Quarterly Review",
            "subtitle": "Generated by Craft Agent",
            "properties": {"title": "Quarterly Review", "author": "Craft Agent"},
            "slideSize": {"width": 13.333, "height": 7.5},
            "theme": {
                "fontName": "Arial", "fontSize": 18, "titleFontSize": 28,
                "textColor": "1F2937", "accentColor": "2563EB",
                "backgroundColor": "FFFFFF",
            },
            "slides": [{
                "title": "Performance",
                "notes": "Discuss the regional outlier.",
                "elements": [
                    {"type": "text", "text": "Generated summary", "x": 0.8, "y": 1.4, "width": 4.2, "height": 0.5, "bold": True},
                    {"type": "shape", "shape": "roundedRectangle", "text": "+24% growth", "x": 0.8, "y": 2.1, "width": 4.2, "height": 0.8, "fill": "DBEAFE"},
                    {"type": "image", "path": str(image), "x": 0.8, "y": 3.2, "width": 0.3, "height": 0.3},
                    {"type": "table", "x": 0.8, "y": 4.0, "width": 4.4, "height": 2.0,
                     "rows": [["Region", "Q1"], ["North", 120], ["South", 98]]},
                    {"type": "chart", "chartType": "column", "title": "Revenue", "x": 6.0, "y": 1.5, "width": 6.2, "height": 4.5,
                     "categories": ["North", "South"], "series": [{"name": "Q1", "values": [120, 98]}]},
                ],
            }, {
                "title": "Layout audit fixture",
                "elements": [
                    {"type": "shape", "shape": "rectangle", "x": 12.8, "y": 2.0, "width": 1.0, "height": 1.0},
                    {"type": "text", "text": "Overlap A", "x": 1.0, "y": 2.0, "width": 2.0, "height": 1.0},
                    {"type": "text", "text": "Overlap B", "x": 2.0, "y": 2.5, "width": 2.0, "height": 1.0},
                ],
            }],
        }), encoding="utf-8")
        deck = self.tmpdir / "structured.pptx"
        created = self.run_tool("create", "--json-data", str(spec), "-o", str(deck))
        self.assertEqual(created.returncode, 0, msg=created.stderr)

        info = self.run_tool("info", str(deck))
        self.assertEqual(info.returncode, 0, msg=info.stderr)
        metadata = json.loads(info.stdout)
        self.assertEqual(metadata["slide_count"], 3)
        self.assertEqual(metadata["title"], "Quarterly Review")
        self.assertEqual(metadata["author"], "Craft Agent")
        self.assertEqual(metadata["slides"][1]["table_count"], 1)
        self.assertEqual(metadata["slides"][1]["chart_count"], 1)
        self.assertEqual(metadata["slides"][1]["image_count"], 1)
        self.assertIn("x", metadata["slides"][1]["shapes"][0])

        lint = self.run_tool("lint", str(deck))
        self.assertEqual(lint.returncode, 0, msg=lint.stderr)
        issues = json.loads(lint.stdout)["issues"]
        self.assertIn("off-page", {issue["type"] for issue in issues})
        self.assertIn("overlap", {issue["type"] for issue in issues})
        strict_lint = self.run_tool("lint", str(deck), "--fail-on-issues")
        self.assertEqual(strict_lint.returncode, 2)

        contact_sheet = self.tmpdir / "structured.svg"
        rendered = self.run_tool("render", str(deck), "-o", str(contact_sheet), "--columns", "2")
        self.assertEqual(rendered.returncode, 0, msg=rendered.stderr)
        svg = contact_sheet.read_text(encoding="utf-8")
        self.assertIn("<svg", svg)
        self.assertIn("[chart]", svg)

        extracted = self.run_tool("extract", str(deck))
        self.assertEqual(extracted.returncode, 0, msg=extracted.stderr)
        self.assertIn("Generated summary", extracted.stdout)
        self.assertIn("Region | Q1", extracted.stdout)
        self.assertIn("Discuss the regional outlier", extracted.stdout)


if __name__ == "__main__":
    unittest.main()
